# Generated by Django 3.1.7 on 2021-02-23 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_process'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='manager',
        ),
        migrations.RemoveField(
            model_name='team',
            name='qa',
        ),
        migrations.RemoveField(
            model_name='team',
            name='tl',
        ),
    ]
