# Generated by Django 3.1.7 on 2021-02-26 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_monitoringformleadsadvanceconsultants_monitoringformleadsallenconsulting_monitoringformleadscitysecu'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='am',
            field=models.CharField(default='testam', max_length=50),
        ),
    ]
