# Generated by Django 3.1.3 on 2020-11-09 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_auto_20201109_1842'),
    ]

    operations = [
        migrations.AddField(
            model_name='coaching',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
