# Generated by Django 3.1.7 on 2021-02-28 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_profile_am'),
    ]

    operations = [
        migrations.RenameField(
            model_name='famehousemonitoringform',
            old_name='service',
            new_name='am',
        ),
        migrations.RenameField(
            model_name='famehousemonitoringform',
            old_name='macros_1',
            new_name='am_id',
        ),
        migrations.RemoveField(
            model_name='famehousemonitoringform',
            name='concept',
        ),
        migrations.RemoveField(
            model_name='famehousemonitoringform',
            name='reason_for_failure',
        ),
        migrations.AddField(
            model_name='famehousemonitoringform',
            name='ce_1',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='famehousemonitoringform',
            name='ce_2',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='famehousemonitoringform',
            name='ce_3',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='famehousemonitoringform',
            name='ce_4',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='famehousemonitoringform',
            name='ce_5',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='famehousemonitoringform',
            name='sh2_2',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='famehousemonitoringform',
            name='sh_1',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='famehousemonitoringform',
            name='sh_3',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='famehousemonitoringform',
            name='team_lead_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='famehousemonitoringform',
            name='ticket_type',
            field=models.CharField(default='na', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='famehousemonitoringform',
            name='ze_1',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='famehousemonitoringform',
            name='ze_2',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='famehousemonitoringform',
            name='ze_3',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='famehousemonitoringform',
            name='ze_4',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
