# Generated by Django 3.1.7 on 2021-02-28 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_auto_20210228_1745'),
    ]

    operations = [
        migrations.RenameField(
            model_name='famehousemonitoringform',
            old_name='sh2_2',
            new_name='sh_2',
        ),
    ]
