# Generated by Django 3.1.3 on 2020-11-12 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_auto_20201110_1012'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutboundMonitoringForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('associate_name', models.CharField(max_length=50)),
                ('emp_id', models.IntegerField()),
                ('qa', models.CharField(max_length=50)),
                ('team_lead', models.CharField(max_length=50)),
                ('customer_name', models.CharField(max_length=50)),
                ('customer_contact', models.IntegerField()),
                ('call_date', models.DateField()),
                ('audit_date', models.DateField()),
                ('campaign', models.CharField(max_length=100)),
                ('zone', models.CharField(max_length=60)),
                ('concept', models.CharField(max_length=60)),
                ('call_duration', models.IntegerField()),
                ('opening_1', models.IntegerField()),
                ('opening_2', models.IntegerField()),
                ('softskill_1', models.IntegerField()),
                ('softskill_2', models.IntegerField()),
                ('softskill_3', models.IntegerField()),
                ('softskill_4', models.IntegerField()),
                ('softskill_5', models.IntegerField()),
                ('softskill_6', models.IntegerField()),
                ('business_1', models.IntegerField()),
                ('business_2', models.IntegerField()),
                ('business_3', models.IntegerField()),
                ('closing_1', models.IntegerField()),
                ('closing_2', models.IntegerField()),
                ('compliance_1', models.IntegerField()),
                ('compliance_2', models.IntegerField()),
                ('compliance_3', models.IntegerField()),
                ('total_score', models.IntegerField()),
                ('compliance', models.IntegerField()),
                ('areas_improvement', models.TextField()),
                ('opening_total', models.IntegerField()),
                ('softskill_total', models.IntegerField()),
                ('business_total', models.IntegerField()),
                ('closing_total', models.IntegerField()),
                ('compliance_total', models.IntegerField()),
                ('positives', models.TextField()),
                ('comments', models.TextField()),
            ],
        ),
    ]
