# Generated by Django 3.1.7 on 2021-03-01 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0007_auto_20210228_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='famehousemonitoringform',
            name='ce_total',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='famehousemonitoringform',
            name='sh_total',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='famehousemonitoringform',
            name='ze_total',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='famehousemonitoringform',
            name='overall_score',
            field=models.IntegerField(null=True),
        ),
    ]
