# Generated by Django 3.1.3 on 2020-11-16 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0008_auto_20201113_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='outboundmonitoringform',
            name='added_by',
            field=models.CharField(default='TestUser', max_length=30),
            preserve_default=False,
        ),
    ]
