# Generated by Django 3.1.3 on 2020-11-16 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0009_outboundmonitoringform_added_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='outboundmonitoringform',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
