# Generated by Django 3.1.7 on 2021-03-01 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0009_auto_20210301_1058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='famehousemonitoringform',
            name='am_id',
        ),
    ]
