# Generated by Django 3.1.7 on 2021-03-01 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0010_remove_famehousemonitoringform_am_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='famehousemonitoringform',
            name='team_lead_id',
        ),
    ]
