# Generated by Django 3.1.3 on 2020-11-16 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0010_outboundmonitoringform_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Coaching',
        ),
    ]
