# Generated by Django 3.1.7 on 2021-03-01 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0011_remove_famehousemonitoringform_team_lead_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='process',
            field=models.CharField(choices=[('Fame House', 'Fame House')], max_length=100),
        ),
    ]
