# Generated by Django 3.1.3 on 2020-11-16 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0011_delete_coaching'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.EmailField(default='test@ecpl.com', max_length=254),
        ),
    ]
