# Generated by Django 3.1.3 on 2020-11-19 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0012_auto_20201116_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='outboundmonitoringform',
            name='closed_date',
            field=models.DateField(null=True),
        ),
    ]
