# Generated by Django 3.1.7 on 2021-03-01 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0012_auto_20210301_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='emp_desi',
            field=models.CharField(choices=[('CRO', 'CRO'), ('Patrolling officer', 'Patrolling officer'), ('AM', 'AM'), ('Trainer', 'Trainer'), ('AD', 'AD'), ('Manager', 'Manager'), ('Service Delivery Manager', 'Service Delivery Manager'), ('CC Team', 'CC Team'), ('BD', 'BD'), ('MIS', 'MIS'), ('Data Analyst', 'Data Analyst'), ('Team Leader', 'Team Leader'), ('QA', 'QA'), ('ATL', 'ATL'), ('SME', 'SME')], max_length=50),
        ),
    ]
