# Generated by Django 3.1.7 on 2021-03-01 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0013_auto_20210301_1210'),
    ]

    operations = [
        migrations.AddField(
            model_name='famehousemonitoringform',
            name='week',
            field=models.CharField(default='Week1', max_length=20),
            preserve_default=False,
        ),
    ]
