# Generated by Django 3.1.7 on 2021-03-01 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0014_famehousemonitoringform_week'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmonitoringformeva',
            name='am',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='chatmonitoringformeva',
            name='week',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='chatmonitoringformpodfather',
            name='am',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='chatmonitoringformpodfather',
            name='week',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='flamonitoringform',
            name='am',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='flamonitoringform',
            name='week',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='inboundmonitoringformnucleusmedia',
            name='am',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='inboundmonitoringformnucleusmedia',
            name='week',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='mastermonitoringformgetaratespsecu',
            name='am',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='mastermonitoringformgetaratespsecu',
            name='week',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='mastermonitoringformmovementinsurance',
            name='am',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='mastermonitoringformmovementinsurance',
            name='week',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='mastermonitoringformmtcosmetics',
            name='am',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='mastermonitoringformmtcosmetics',
            name='week',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='mastermonitoringformtonnchatsemail',
            name='am',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='mastermonitoringformtonnchatsemail',
            name='week',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='mastermonitoringformtonncoainboundcalls',
            name='am',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='mastermonitoringformtonncoainboundcalls',
            name='week',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='monitoringformleadsaadhyasolution',
            name='am',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='monitoringformleadsaadhyasolution',
            name='week',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='monitoringformleadsadvanceconsultants',
            name='am',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='monitoringformleadsadvanceconsultants',
            name='week',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='monitoringformleadsallenconsulting',
            name='am',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='monitoringformleadsallenconsulting',
            name='week',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='monitoringformleadscitysecurity',
            name='am',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='monitoringformleadscitysecurity',
            name='week',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='monitoringformleadscts',
            name='am',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='monitoringformleadscts',
            name='week',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='monitoringformleadsgetarates',
            name='am',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='monitoringformleadsgetarates',
            name='week',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='monitoringformleadsinfothinkllc',
            name='am',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='monitoringformleadsinfothinkllc',
            name='week',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='monitoringformleadsinsalvage',
            name='am',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='monitoringformleadsinsalvage',
            name='week',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='monitoringformleadslouisville',
            name='am',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='monitoringformleadslouisville',
            name='week',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='monitoringformleadsmedicare',
            name='am',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='monitoringformleadsmedicare',
            name='week',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='monitoringformleadspsecu',
            name='am',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='monitoringformleadspsecu',
            name='week',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='monitoringformleadssystem4',
            name='am',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='monitoringformleadssystem4',
            name='week',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='monitoringformleadstentamusfood',
            name='am',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='monitoringformleadstentamusfood',
            name='week',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='monitoringformleadstentamuspet',
            name='am',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='monitoringformleadstentamuspet',
            name='week',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='printerpixmastermonitoringformchatsemail',
            name='am',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='printerpixmastermonitoringformchatsemail',
            name='week',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='printerpixmastermonitoringforminboundcalls',
            name='am',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='printerpixmastermonitoringforminboundcalls',
            name='week',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='witdigitalmasteringmonitoringform',
            name='am',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='witdigitalmasteringmonitoringform',
            name='week',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='famehousemonitoringform',
            name='am',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='famehousemonitoringform',
            name='week',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
