# Generated by Django 3.1.7 on 2021-03-04 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0015_auto_20210301_2222'),
    ]

    operations = [
        migrations.AddField(
            model_name='famehousemonitoringform',
            name='fatal',
            field=models.BooleanField(default=False),
        ),
    ]
