# Generated by Django 3.1.7 on 2021-03-08 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0016_famehousemonitoringform_fatal'),
    ]

    operations = [
        migrations.AddField(
            model_name='inboundmonitoringformnucleusmedia',
            name='fatal',
            field=models.BooleanField(default=False),
        ),
    ]
