# Generated by Django 3.1.3 on 2020-11-24 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0017_remove_emailmonitoringform_customer_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='team',
            field=models.CharField(choices=[('Noom', 'Noom'), ('Aadya Solutions', 'Aadya Solutions'), ('UPS CLP', 'UPS CLP')], max_length=50),
        ),
    ]
