# Generated by Django 3.1.7 on 2021-03-11 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0018_auto_20210311_1231'),
    ]

    operations = [
        migrations.AddField(
            model_name='famehousemonitoringform',
            name='fatal_count',
            field=models.IntegerField(default=0),
        ),
    ]
