# Generated by Django 3.1.7 on 2021-03-24 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0021_auto_20210311_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mastermonitoringformgetaratespsecu',
            name='process',
            field=models.CharField(default='PSECU', max_length=50),
        ),
    ]
