# Generated by Django 3.1.3 on 2020-11-26 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0022_auto_20201126_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inboundmonitoringform',
            name='closed_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
