# Generated by Django 3.1.7 on 2021-03-24 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0022_auto_20210324_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='famehousemonitoringform',
            name='disput_status',
            field=models.BooleanField(default=False),
        ),
    ]
