# Generated by Django 3.1.3 on 2020-11-26 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0024_auto_20201126_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inboundmonitoringform',
            name='closed_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='outboundmonitoringform',
            name='closed_date',
            field=models.DateField(null=True),
        ),
    ]
