# Generated by Django 3.1.7 on 2021-04-02 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0024_auto_20210324_1742'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField(unique=True)),
                ('username', models.IntegerField()),
                ('password', models.CharField(max_length=30)),
            ],
        ),
    ]
