# Generated by Django 3.1.3 on 2020-12-01 18:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employees', '0031_auto_20201201_2323'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='mgr',
        ),
        migrations.AlterField(
            model_name='team',
            name='qa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
