# Generated by Django 3.1.7 on 2021-04-08 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0031_auto_20210407_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmonitoringformeva',
            name='process',
            field=models.CharField(default='Noom-EVA', max_length=50),
        ),
        migrations.AlterField(
            model_name='chatmonitoringformpodfather',
            name='process',
            field=models.CharField(default='Noom-POD', max_length=50),
        ),
        migrations.AlterField(
            model_name='mastermonitoringformmovementinsurance',
            name='process',
            field=models.CharField(default='Movement of Insurance', max_length=50),
        ),
        migrations.AlterField(
            model_name='mastermonitoringformmtcosmetics',
            name='process',
            field=models.CharField(default='MT Cosmetic', max_length=50),
        ),
        migrations.AlterField(
            model_name='mastermonitoringformtonnchatsemail',
            name='process',
            field=models.CharField(default='Tonn Chat Email', max_length=50),
        ),
        migrations.AlterField(
            model_name='monitoringformleadsaadhyasolution',
            name='process',
            field=models.CharField(default='AAdya', max_length=50),
        ),
        migrations.AlterField(
            model_name='monitoringformleadsinfothinkllc',
            name='process',
            field=models.CharField(default='Info Think LLC', max_length=50),
        ),
        migrations.AlterField(
            model_name='printerpixmastermonitoringformchatsemail',
            name='process',
            field=models.CharField(default='Printer Pix Chat Email', max_length=50),
        ),
    ]
