# Generated by Django 3.1.3 on 2020-12-01 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0034_auto_20201201_2355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='team',
            field=models.CharField(choices=[('Noom', 'Noom'), ('Aadya Solutions', 'Aadya Solutions'), ('UPS CLP', 'UPS CLP'), ('Gardening Express', 'Gardening Express'), ('Maxwell Properties', 'Maxwell Properties'), ('Gubagoo', 'Gubagoo'), ('Digital Swiss Gold', 'Digital Swiss Gold'), ('Digital Signage', 'Digital Signage'), ('Success Systems', 'Success Systems'), ('Advancement Consulting ', 'Advancement Consulting'), ('Insalvage', 'Insalvage'), ('Medicare', 'Medicare'), ('Printerpix', 'Printerpix'), ('Printerpix Training', 'Printerpix Training'), ('First Look Appraisal', 'First Look Appraisal'), ('TCA Counseling Group', 'TCA Counseling Group'), ('Advit Sahdev Marketing', 'Advit Sahdev Marketing'), ('AKDY', 'AKDY'), ('AKDY Training', 'AKDY Training'), ('Monster Lead Group', 'Monster Lead Group'), ('Fame House', 'Fame House'), ('Lecanto Green coffee', 'Lecanto Green coffee'), ('Micro Distributing', 'Micro Distributing'), ('Aditya Birla', 'Aditya Birla'), ('Aditya Birla Cellulose', 'Aditya Birla Cellulose'), ('Aditya Birla Cellulose Training', 'Aditya Birla Cellulose Training'), ('City Security Services', 'City Security Services'), ('Active Sports Club', 'Active Sports Club'), ('Aditya Birla Sampling Team', 'Aditya Birla Sampling Team'), ('Aditya Birla Sampling Team Trainig', 'Aditya Birla Sampling Team Trainig'), ('Bigo - IMO Group Chat', 'Bigo - IMO Group Chat'), ('Bigo Monitor Team', 'Bigo Monitor Team'), ('Daniel Wellington', 'Daniel Wellington'), ('Option Matrix', 'Option Matrix'), ('Info Think LLC', 'Info Think LLC'), ('MT Cosmetics', 'MT Cosmetics'), ("Something's Brewing", "Something's Brewing"), ('WIT Digital', 'WIT Digital'), ('Sync Treasury LLC', 'Sync Treasury LLC'), ('SANA GAMING CONSULTING', 'SANA GAMING CONSULTING'), ('GrayStone LLC', 'GrayStone LLC'), ('Kaapi Machines', 'Kaapi Machines'), ('Richmond Assets & Holdings', 'Richmond Assets & Holdings'), ('US Home Exterior', 'US Home Exterior'), ('Pre Management Leicester LTD', 'Pre Management Leicester LTD'), ('American Income Life', 'American Income Life'), ('Life Alarm Services', 'Life Alarm Services'), ('ERI Global', 'ERI Global'), ('Allen Consulting group', 'Allen Consulting group'), ('Jeffery Tan ', 'Jeffery Tan '), ('Student Life', 'Student Life'), ('Career Transition Specialist', 'Career Transition Specialist'), ('Golden Eye Tech CCTV', 'Golden Eye Tech CCTV'), ('MOVEMENT INSURANCE', 'MOVEMENT INSURANCE'), ('Nucleus Media', 'Nucleus Media'), ('PSECU', 'PSECU'), ('Tentamus', 'Tentamus'), ('L&D', 'L&D'), ('Get A Rate', 'Get A Rate'), ('Mayfair Acct and Wealth', 'Mayfair Acct and Wealth'), ('Superking', 'Superking'), ('Millionaires Group', 'Millionaires Group'), ('PROTOSTAR', 'PROTOSTAR'), ('MESSE FRANKFURT', 'MESSE FRANKFURT'), ('System 4', 'System 4'), ('Naffa Innovations Pvt Ltd', 'Naffa Innovations Pvt Ltd'), ('Support Staff', 'Support Staff'), ('Quality Team', 'Quality Team')], max_length=50),
        ),
    ]
