# Generated by Django 3.1.3 on 2020-12-03 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0036_leadsalesmonitoringform'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmonitorinform',
            name='business_3',
            field=models.CharField(default='yes', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chatmonitorinform',
            name='ce_10',
            field=models.CharField(default='yes', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chatmonitorinform',
            name='ce_11',
            field=models.CharField(default='yes', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chatmonitorinform',
            name='ce_7',
            field=models.CharField(default='yes', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chatmonitorinform',
            name='ce_8',
            field=models.CharField(default='yes', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chatmonitorinform',
            name='ce_9',
            field=models.CharField(default='yes', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chatmonitorinform',
            name='compliance_4',
            field=models.CharField(default='yes', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chatmonitorinform',
            name='compliance_5',
            field=models.CharField(default='yes', max_length=10),
            preserve_default=False,
        ),
    ]
