# Generated by Django 3.1.3 on 2020-12-09 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0038_auto_20201209_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmonitoringformeva',
            name='ce_1',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='chatmonitoringformeva',
            name='ce_2',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='chatmonitoringformeva',
            name='ce_3',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='chatmonitoringformeva',
            name='ce_4',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='chatmonitoringformeva',
            name='compliance_1',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='chatmonitoringformeva',
            name='compliance_2',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='chatmonitoringformeva',
            name='compliance_3',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='chatmonitoringformeva',
            name='compliance_4',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='chatmonitoringformeva',
            name='compliance_5',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='chatmonitoringformeva',
            name='compliance_6',
            field=models.IntegerField(),
        ),
    ]
