# Generated by Django 3.1.3 on 2020-12-10 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0041_inboundmonitoringform'),
    ]

    operations = [
        migrations.AddField(
            model_name='inboundmonitoringform',
            name='business_2',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
