# Generated by Django 3.1.3 on 2020-12-17 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0042_inboundmonitoringform_business_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmonitoringformeva',
            name='manager',
            field=models.CharField(default='test', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chatmonitoringformeva',
            name='manager_id',
            field=models.IntegerField(default=111111111111111),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chatmonitoringformpodfather',
            name='manager',
            field=models.CharField(default='test', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chatmonitoringformpodfather',
            name='manager_id',
            field=models.IntegerField(default=1111111111),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inboundmonitoringform',
            name='manager',
            field=models.CharField(default='test', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inboundmonitoringform',
            name='manager_id',
            field=models.IntegerField(default=1111111111),
            preserve_default=False,
        ),
    ]
