# Generated by Django 3.1.3 on 2020-12-18 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0043_auto_20201217_1131'),
    ]

    operations = [
        migrations.CreateModel(
            name='FameHouseMonitoringForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.IntegerField()),
                ('associate_name', models.CharField(max_length=50)),
                ('qa', models.CharField(max_length=50)),
                ('team_lead', models.CharField(max_length=50)),
                ('ticket_no', models.IntegerField()),
                ('trans_date', models.DateField()),
                ('audit_date', models.DateField()),
                ('campaign', models.CharField(max_length=100)),
                ('service', models.CharField(max_length=50)),
                ('concept', models.CharField(max_length=60)),
                ('manager', models.CharField(max_length=50)),
                ('manager_id', models.IntegerField()),
                ('macros_1', models.IntegerField()),
                ('reason_for_failure', models.TextField()),
                ('areas_improvement', models.TextField()),
                ('positives', models.TextField()),
                ('comments', models.TextField()),
                ('added_by', models.CharField(max_length=30)),
                ('status', models.BooleanField(default=False)),
                ('closed_date', models.DateTimeField(null=True)),
                ('emp_comments', models.TextField(null=True)),
                ('overall_score', models.IntegerField()),
            ],
        ),
    ]
