# Generated by Django 3.1.3 on 2020-12-22 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0047_chatandemailmonform'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatandemailmonform',
            name='business_total',
            field=models.IntegerField(null=True),
        ),
    ]
