# Generated by Django 3.1.3 on 2020-12-26 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0048_chatandemailmonform_business_total'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LeadsandSalesMonForm',
            new_name='MasterMonitoringFormGetaRatesPSECU',
        ),
    ]
