# Generated by Django 3.1.3 on 2020-12-26 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0049_auto_20201226_1641'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InboundMonitoringForm',
            new_name='InboundMonitoringFormNucleusMedia',
        ),
    ]
