# Generated by Django 3.1.3 on 2021-01-04 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0055_auto_20201228_1155'),
    ]

    operations = [
        migrations.RenameField(
            model_name='printerpixmastermonitoringformchatsemail',
            old_name='call_duration',
            new_name='duration',
        ),
        migrations.RenameField(
            model_name='printerpixmastermonitoringformchatsemail',
            old_name='call_date',
            new_name='trans_date',
        ),
    ]
