# Generated by Django 3.1.3 on 2021-01-05 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0056_auto_20210104_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitoringformleadsaadhyasolution',
            name='softskill_total',
            field=models.IntegerField(null=True),
        ),
    ]
