# Generated by Django 3.1.3 on 2021-01-27 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0057_monitoringformleadsaadhyasolution_softskill_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmonitoringformeva',
            name='process',
            field=models.CharField(default='EVA Chat', max_length=50),
        ),
    ]
