# Generated by Django 3.1.3 on 2021-01-27 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0058_chatmonitoringformeva_process'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmonitoringformpodfather',
            name='process',
            field=models.CharField(default='Pod Father', max_length=50),
        ),
        migrations.AddField(
            model_name='famehousemonitoringform',
            name='process',
            field=models.CharField(default='Fame House', max_length=50),
        ),
        migrations.AddField(
            model_name='flamonitoringform',
            name='process',
            field=models.CharField(default='FLA', max_length=50),
        ),
        migrations.AddField(
            model_name='inboundmonitoringformnucleusmedia',
            name='process',
            field=models.CharField(default='Nucleus', max_length=50),
        ),
        migrations.AddField(
            model_name='mastermonitoringformgetaratespsecu',
            name='process',
            field=models.CharField(default='Get a Rates PSECU', max_length=50),
        ),
        migrations.AddField(
            model_name='mastermonitoringformmovementinsurance',
            name='process',
            field=models.CharField(default='Mov Insurance', max_length=50),
        ),
        migrations.AddField(
            model_name='mastermonitoringformmtcosmetics',
            name='process',
            field=models.CharField(default='Mt Cosmetic', max_length=50),
        ),
        migrations.AddField(
            model_name='mastermonitoringformtonnchatsemail',
            name='process',
            field=models.CharField(default='Tonn Chat', max_length=50),
        ),
        migrations.AddField(
            model_name='mastermonitoringformtonncoainboundcalls',
            name='process',
            field=models.CharField(default='Tonn Coa', max_length=50),
        ),
        migrations.AddField(
            model_name='monitoringformleadsaadhyasolution',
            name='process',
            field=models.CharField(default='Aadya', max_length=50),
        ),
        migrations.AddField(
            model_name='printerpixmastermonitoringformchatsemail',
            name='process',
            field=models.CharField(default='Printer Pix Chat', max_length=50),
        ),
        migrations.AddField(
            model_name='printerpixmastermonitoringforminboundcalls',
            name='process',
            field=models.CharField(default='Printer Pix Inbound', max_length=50),
        ),
        migrations.AddField(
            model_name='witdigitalmasteringmonitoringform',
            name='process',
            field=models.CharField(default='Wit Digital', max_length=50),
        ),
    ]
