# Generated by Django 3.1.3 on 2021-02-09 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0059_auto_20210127_2314'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='manager',
            field=models.CharField(default='Testmanager', max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='process',
            field=models.CharField(default='Training', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='team_lead',
            field=models.CharField(default='Testlead', max_length=50),
        ),
    ]
